### ISSUE TITLE
[Bug]: AuthenticationError, RetryEror

### ISSUE THREAD

**Issue by Ashish5869** [jerryjliu/llama_index#6502] opened 2023-06-19 06:50 UTC
### Bug Description

```
index = GPTVectorStoreIndex.from_documents(
    document,
    storage_context=storage_context,
    service_context=service_context
)


or 


index = GPTVectorStoreIndex.from_documents(
    [],
    storage_context=storage_context,
    service_context=service_context
)

query_engine = index.as_query_engine()
resposnse = query_engine.query()

Error:
AuthenticationError                       Traceback (most recent call last)

AuthenticationError: No API key provided. You can set your API key in code using 'openai.api_key = <API-KEY>', or you can set the environment variable OPENAI_API_KEY=<API-KEY>). If your API key is stored in a file, you can point the openai module at it with 'openai.api_key_path = <PATH>'. You can generate API keys in the OpenAI web interface. See https://platform.openai.com/account/api-keys for details, or email support@openai.com if you have any questions.

RetryError: RetryError[<Future at 0x7f6bdeb32b30 state=finished raised AuthenticationError>
```

### Version

0.6.25, 0.6.25post1, 0.6.26 and 0.6.27

### Steps to Reproduce

while indexing the document

**Comment by juangon** [comment] 2023-06-19 11:46
Maybe duplicated of https://github.com/jerryjliu/llama_index/issues/6458

**Comment by Disiok** [comment] 2023-06-20 18:16
Not sure what the cause is yet. Will investigate. But closing as duplicate of https://github.com/jerryjliu/llama_index/issues/6458

**Closed by Disiok** 2023-06-20 18:16 UTC
Labels: bug, triage
