### ISSUE TITLE
how charge openai api url

### ISSUE THREAD

**Issue by zbsean** [jerryjliu/llama_index#701] opened 2023-03-11 10:44 UTC
my app connect by proxy to openai,  so the openai addres not api.openai.com.  how charge it ?

**Comment by kenn** [comment] 2023-03-12 00:56
Just set the `OPENAI_API_BASE` environment variable like this

```bash
OPENAI_API_BASE = 'https://domain.com/api'
```

**Comment by Disiok** [comment] 2023-03-16 17:49
Duplicate of https://github.com/jerryjliu/llama_index/issues/640

**Closed by Disiok** 2023-03-16 17:49 UTC

**Comment by chrischjh** [comment] 2023-03-17 06:57
> 

It works by setting env vars, but the env var has to be set before importing llama_index libs
