### ISSUE TITLE
[Bug]: fail to parse nodes with relationships defined from qdrant

### ISSUE THREAD

**Issue by rxue92** [jerryjliu/llama_index#6637] opened 2023-06-29 04:31 UTC
### Bug Description

Here is the problem I encountered: I have created Document type nodes and utilized them to establish a VectorStoreIndex using qdrant as the vector store. The process of creating the index went smoothly, and the nodes were successfully stored in qdrant. However, when I attempt to query the index, it loads the data from qdrant and attempts to parse it into a TextNode type, resulting in an error.

Interestingly, the code functions properly when no relationship is defined.

```python
# vetore_stores/utils.py
def metadata_dict_to_node(metadata: dict) -> TextNode:
    """Common logic for loading Node data from metadata dict."""
    node_json = metadata.get("_node_content", None)
    if node_json is None:
        raise ValueError("Node content not found in metadata dict.")

    return TextNode.parse_raw(node_json)  # <--
``` 

### Version

0.6.35

### Steps to Reproduce

```python
from llama_index import Document
from llama_index.schema import NodeRelationship
from qdrant_client import QdrantClient
from llama_index.vector_stores import QdrantVectorStore
from qdrant_client.http.models import Distance, VectorParams
from typing import List
from llama_index import StorageContext, VectorStoreIndex
from llama_index.vector_stores import QdrantVectorStore
from llama_index import load_index_from_storage
import logging
import sys

logging.basicConfig(stream=sys.stdout, level=logging.DEBUG)

def unit_vector(idx: int) -> List[float]:
    arr = [0]*1536
    arr[idx] = 1
    return arr

def create_collection(client: QdrantClient, collection_name: str) -> None:
    resp = client.get_collections()
    found = False
    for col in resp.collections:
        if col.name == collection_name:
            found = True
            break

    if found:
        print(f"collection [{collection_name}] exist!")
        print(client.get_collection(collection_name))
    else:
        success = client.create_collection(
            collection_name=collection_name,
            vectors_config=VectorParams(size=1536, distance=Distance.COSINE),
        )
        print(f"create collection [{collection_name}] success: {success}")


def qdrant_client() -> QdrantClient:
    qd_host = "host"
    qd_port = 1234
    qd_api_key = "key"

    # Creating a Qdrant vector store
    client = QdrantClient(
        host=qd_host,
        port=qd_port,
        api_key=qd_api_key,
        https=False
    )
    return client


uuid1 = "43ac3cc4-eef1-4f66-9d27-b8eef2681596"
uuid2 = "c5f6feb0-36b7-4442-8a6f-398c80253e1e"

def make_nodes() -> List[Document]:
    doc1 = Document(
        text="2023/06/27: learn about llamaindex",
        metadata={"docType": "diary", "mood": "happy"},
        doc_id=uuid1
    )

    doc2 = Document(
        text="2023/06/28: confused about vectore store",
        metadata={"docType": "diary", "mood": "confusing"},
        doc_id=uuid2
    )
    
    # defined as Document, parsed as TextNode
    doc1.relationships[NodeRelationship.NEXT] = doc2.node_id
    doc2.relationships[NodeRelationship.PREVIOUS] = doc1.node_id

    # just for saving money
    doc1.embedding = unit_vector(0)
    doc2.embedding = unit_vector(1)

    nodes = [doc1, doc2]

    return nodes

def replay():
    collection_name = "test"

    client = qdrant_client()

    client.delete_collection(collection_name)

    create_collection(client, collection_name)

    nodes = make_nodes()

    qdrant_vector_store = QdrantVectorStore(
        client=client,
        collection_name=collection_name,
    )

    storage_ctx = StorageContext.from_defaults(vector_store=qdrant_vector_store)

    vec_index = VectorStoreIndex(nodes, storage_context=storage_ctx)

    vec_index.set_index_id("vec_index")

    for t in client.scroll(collection_name, limit=5)[0]:
        print(t)
    # failed here if relationships are defined
    print(vec_index.as_query_engine(verbose=True).query("what have i done on 2023/06/27"))

    vec_index.storage_context.persist()

    loaded_vec_index = load_index_from_storage(storage_ctx, index_id="vec_index")

   # would fail if last query() was commented
    print(loaded_vec_index.as_query_engine(verbose=True).query("how i feel on June 28th"))


if __name__ == "__main__":
    replay()
```

### Relevant Logs/Tracbacks

```shell
INFO:httpx:HTTP Request: POST http://<qdrant>/collections/test/points/scroll "HTTP/1.1 200 OK"
DEBUG:httpcore.http11:receive_response_body.started request=<Request [b'POST']>
DEBUG:httpcore.http11:receive_response_body.complete
DEBUG:httpcore.http11:response_closed.started
DEBUG:httpcore.http11:response_closed.complete
id='43ac3cc4-eef1-4f66-9d27-b8eef2681596' payload={'_node_content': '{"id_": "43ac3cc4-eef1-4f66-9d27-b8eef2681596", "embedding": null, "metadata": {"docType": "diary", "mood": "happy"}, "excluded_embed_metadata_keys": [], "excluded_llm_metadata_keys": [], "relationships": {"3": "c5f6feb0-36b7-4442-8a6f-398c80253e1e"}, "hash": "a96e9f994571730ade8b16fea52d8fc79cddd55529c8a256bde04597b8603e17", "text": "2023/06/27: learn 
about llamaindex", "start_char_idx": null, "end_char_idx": null, "text_template": "{metadata_str}\\n\\n{content}", "metadata_template": "{key}: {value}", "metadata_seperator": "\\n"}', 'docType': 'diary', 'doc_id': 'None', 'document_id': 'None', 'mood': 'happy', 'ref_doc_id': 'None'} vector=None
id='c5f6feb0-36b7-4442-8a6f-398c80253e1e' payload={'_node_content': '{"id_": "c5f6feb0-36b7-4442-8a6f-398c80253e1e", "embedding": null, "metadata": {"docType": "diary", "mood": "confusing"}, "excluded_embed_metadata_keys": [], "excluded_llm_metadata_keys": [], "relationships": {"2": "43ac3cc4-eef1-4f66-9d27-b8eef2681596"}, "hash": "92d1382ef27fa31890d11ae25bfcb166e99283a63b1746cfded8cba580bfd103", "text": "2023/06/28: confused about vectore store", "start_char_idx": null, "end_char_idx": null, "text_template": "{metadata_str}\\n\\n{content}", "metadata_template": "{key}: {value}", "metadata_seperator": "\\n"}', 'docType': 'diary', 'doc_id': 'None', 'document_id': 'None', 'mood': 'confusing', 'ref_doc_id': 'None'} vector=None
DEBUG:openai:message='Request to OpenAI API' method=post path=https://api.openai.com/v1/embeddings
DEBUG:openai:api_version=None data='{"input": ["what have i done on 2023/06/27"], "model": "text-embedding-ada-002", "encoding_format": "base64"}' message='Post details'
DEBUG:urllib3.util.retry:Converted retries value: 2 -> Retry(total=2, connect=None, read=None, redirect=None, status=None)
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.openai.com:443
DEBUG:urllib3.connectionpool:https://api.openai.com:443 "POST /v1/embeddings HTTP/1.1" 200 None
DEBUG:openai:message='OpenAI API response' path=https://api.openai.com/v1/embeddings processing_ms=112 request_id=9898e56344b07edbaae2616a3c51dca6 response_code=200
DEBUG:httpcore.connection:connect_tcp.started host='127.0.0.1' port=10809 local_address=None timeout=5.0 socket_options=None
DEBUG:httpcore.connection:connect_tcp.complete return_value=<httpcore.backends.sync.SyncStream object at 0x0000022B70BB8310>
DEBUG:httpcore.http11:send_request_headers.started request=<Request [b'POST']>
DEBUG:httpcore.http11:send_request_headers.complete
DEBUG:httpcore.http11:send_request_body.started request=<Request [b'POST']>
DEBUG:httpcore.http11:send_request_body.complete
DEBUG:httpcore.http11:receive_response_headers.started request=<Request [b'POST']>
DEBUG:httpcore.http11:receive_response_headers.complete return_value=(b'HTTP/1.1', 200, b'OK', [(b'Connection', b'close'), (b'Transfer-Encoding', b'chunked'), (b'Content-Encoding', b'gzip'), (b'Content-Type', b'application/json'), (b'Date', b'Thu, 29 Jun 2023 03:51:03 GMT'), (b'Vary', b'accept-encoding, Origin, Access-Control-Request-Method, Access-Control-Request-Headers')])
INFO:httpx:HTTP Request: POST http://<qdrant>/collections/test/points/search "HTTP/1.1 200 OK"
DEBUG:httpcore.http11:receive_response_body.started request=<Request [b'POST']>
DEBUG:httpcore.http11:receive_response_body.complete
DEBUG:httpcore.http11:response_closed.started
DEBUG:httpcore.http11:response_closed.complete
DEBUG:llama_index.vector_stores.qdrant:> Top 2 nodes:
DEBUG:llama_index.vector_stores.qdrant:Failed to parse Node metadata, fallback to legacy logic.
Traceback (most recent call last):
  File "D:\software\Anaconda3\envs\py310\lib\site-packages\llama_index\vector_stores\qdrant.py", line 187, in query
    node = metadata_dict_to_node(payload)
  File "D:\software\Anaconda3\envs\py310\lib\site-packages\llama_index\vector_stores\utils.py", line 61, in metadata_dict_to_node
    return TextNode.parse_raw(node_json)
  File "pydantic\main.py", line 549, in pydantic.main.BaseModel.parse_raw
  File "pydantic\main.py", line 526, in pydantic.main.BaseModel.parse_obj
  File "pydantic\main.py", line 341, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 2 validation errors for TextNode
relationships -> 2
  value is not a valid dict (type=type_error.dict)
relationships -> 2
  value is not a valid list (type=type_error.list)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "d:\code\python\demo\qdrant_fail_to_load.py", line 116, in <module>
    replay()
  File "d:\code\python\demo\qdrant_fail_to_load.py", line 105, in replay
    print(vec_index.as_query_engine(verbose=True).query("what have i done on 2023/06/27"))
  File "D:\software\Anaconda3\envs\py310\lib\site-packages\llama_index\indices\query\base.py", line 23, in query
    response = self._query(str_or_query_bundle)
  File "D:\software\Anaconda3\envs\py310\lib\site-packages\llama_index\query_engine\retriever_query_engine.py", line 142, in _query
    nodes = self._retriever.retrieve(query_bundle)
  File "D:\software\Anaconda3\envs\py310\lib\site-packages\llama_index\indices\base_retriever.py", line 21, in retrieve
    return self._retrieve(str_or_query_bundle)
  File "D:\software\Anaconda3\envs\py310\lib\site-packages\llama_index\token_counter\token_counter.py", line 78, in wrapped_llm_predict
    f_return_val = f(_self, *args, **kwargs)
  File "D:\software\Anaconda3\envs\py310\lib\site-packages\llama_index\indices\vector_store\retrievers\retriever.py", line 84, in _retrieve
    query_result = self._vector_store.query(query, **self._kwargs)
  File "D:\software\Anaconda3\envs\py310\lib\site-packages\llama_index\vector_stores\qdrant.py", line 195, in query
    node = TextNode(
  File "pydantic\main.py", line 341, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for TextNode
text
  none is not an allowed value (type=type_error.none.not_allowed)
```

**Comment by Disiok** [comment] 2023-07-13 23:13
Hmm surprising that it's going through the `backward compatibility` code path. Will look into this.

**Comment by logan-markewich** [comment] 2023-07-14 16:17
@Disiok @rxue92 The way node relationships are defined changed in 0.6.35. Please see the docs here: https://gpt-index.readthedocs.io/en/latest/core_modules/data_modules/documents_and_nodes/usage_nodes.html#defining-and-customizing-nodes

And the `RelatedNodeInfo` class API for reference
https://github.com/jerryjliu/llama_index/blob/77009aa67a50d42b3c0c57af84b5bca8044829ee/llama_index/schema.py#L49

It seems like the backwards compat code path has a small bug though, not sure why it's complaining that text was `None`

**Comment by logan-markewich** [comment] 2023-07-22 01:50
Going to close this for now. My suggestion about changing the relation type should help. 

Further, even though you define `Document` objects, they have the exact same interface (hence, this is likely not the cause of the issue, and the issue is likely the relationships)

Feel free to reach out on discord if you have more issues!

**Closed by logan-markewich** 2023-07-22 01:50 UTC
Labels: bug
