### ISSUE TITLE
Some PDF not working in simpleVector

### ISSUE THREAD

**Issue by ricardoborges** [jerryjliu/llama_index#875] opened 2023-03-24 22:08 UTC
That's random for me, sometimes the index can't be made, any thoughts?

    prompt_helper = PromptHelper(
  File "/home/ricardo/git/PerguntePDF/env/lib/python3.10/site-packages/llama_index/indices/prompt_helper.py", line 51, in __init__
    self._tokenizer = tokenizer or globals_helper.tokenizer
  File "/home/ricardo/git/PerguntePDF/env/lib/python3.10/site-packages/llama_index/utils.py", line 38, in tokenizer
    enc = tiktoken.get_encoding("gpt2")
  File "/home/ricardo/git/PerguntePDF/env/lib/python3.10/site-packages/tiktoken/registry.py", line 63, in get_encoding
    enc = Encoding(**constructor())
  File "/home/ricardo/git/PerguntePDF/env/lib/python3.10/site-packages/tiktoken_ext/openai_public.py", line 11, in gpt2
    mergeable_ranks = data_gym_to_mergeable_bpe_ranks(
  File "/home/ricardo/git/PerguntePDF/env/lib/python3.10/site-packages/tiktoken/load.py", line 95, in data_gym_to_mergeable_bpe_ranks
    assert bpe_ranks == encoder_json_loaded
AssertionError

------------------- code ---------------------------
    max_input_size = 4096
    num_outputs = 256
    max_chunk_overlap = 20
    chunk_size_limit = 600
    prompt_helper = PromptHelper(
        max_input_size, num_outputs, max_chunk_overlap, chunk_size_limit=chunk_size_limit)
    llm_predictor = LLMPredictor(llm=OpenAI(
        temperature=0, model_name="text-davinci-003", max_tokens=num_outputs))
    documents = SimpleDirectoryReader(directory_path).load_data()
    index = GPTSimpleVectorIndex(
        documents, llm_predictor=llm_predictor, prompt_helper=prompt_helper)

    index.save_to_disk(filepath)
    return index

**Comment by Disiok** [comment] 2023-03-25 01:26
Duplicate of https://github.com/jerryjliu/llama_index/issues/738

**Closed by Disiok** 2023-03-25 01:26 UTC
