### ISSUE TITLE
[Bug]: Usage of CustomLLM is broken

### ISSUE THREAD

**Issue by mirth** [jerryjliu/llama_index#6702] opened 2023-07-03 12:54 UTC
### Bug Description

Getting an error when trying to create `ServiceContext` with `CustomLLM`.

### Version

0.6.38.post1

### Steps to Reproduce

```
from llama_index import ServiceContext
from llama_index.llms.custom import CustomLLM
from llama_index.llms.base import CompletionResponse, LLMMetadata, CompletionResponseGen
from typing import Any


context_window = 2048
num_output = 256

class OurLLM(CustomLLM):
    @property
    def metadata(self) -> LLMMetadata:
        return LLMMetadata(
            context_window=context_window, num_output=num_output
        )

    def complete(self, prompt: str, **kwargs: Any) -> CompletionResponse:

        return CompletionResponse(text='sample response')
    
    def stream_complete(self, prompt: str, **kwargs: Any) -> CompletionResponseGen:
        raise NotImplementedError()
    

llm = OurLLM()

service_context = ServiceContext.from_defaults(
    llm=llm, 
    context_window=context_window, 
    num_output=num_output
)
```

### Relevant Logs/Tracbacks

```shell
File "/repro.py", line 30, in <module>
    service_context = ServiceContext.from_defaults(
  File "/Users/user/Library/Python/3.9/lib/python/site-packages/llama_index/indices/service_context.py", line 141, in from_defaults
    llm_metadata=llm_predictor.get_llm_metadata(),
  File "/Users/user/Library/Python/3.9/lib/python/site-packages/llama_index/llm_predictor/base.py", line 189, in get_llm_metadata
    return _get_llm_metadata(self._llm)
  File "/Users/user/Library/Python/3.9/lib/python/site-packages/llama_index/llm_predictor/base.py", line 49, in _get_llm_metadata
    raise ValueError("llm must be an instance of langchain.llms.base.LLM")
```

**Comment by jon-chuang** [comment] 2023-07-03 13:29
Indeed, there should be a branch for custom LLM. CustomLLM have an attribute that is not implemented.

**Comment by jon-chuang** [comment] 2023-07-03 13:35
Actually, I believe the problem is fixed on the latest master. Not sure about latest release.

**Comment by logan-markewich** [comment] 2023-07-03 14:13
Yup, will be fixed in the next release!

**Closed by logan-markewich** 2023-07-03 14:13 UTC
Labels: bug, triage

**Comment by mirth** [comment] 2023-07-04 12:47
On the latest master(99f3127012368cac3450c10b6d30e7942ae1bccd) with sample code from the top comment I'm getting:

```
  File "repro.py", line 27, in <module>
    service_context = ServiceContext.from_defaults(
  File "/home/ubuntu/llama_index/llama_index/indices/service_context.py", line 140, in from_defaults
    prompt_helper = prompt_helper or _get_default_prompt_helper(
  File "/home/ubuntu/llama_index/llama_index/indices/service_context.py", line 42, in _get_default_prompt_helper
    llm_metadata = dataclasses.replace(llm_metadata, context_window=context_window)
  File "/usr/lib/python3.8/dataclasses.py", line 1264, in replace
    raise TypeError("replace() should be called on dataclass instances")
TypeError: replace() should be called on dataclass instances
```

**Comment by mirth** [comment] 2023-07-05 05:32
@logan-markewich could you please reopen the issue? On the latest master it's still broken.
