### ISSUE TITLE
Using load_from_disk does not work for azure implementation of OpenAI

### ISSUE THREAD

**Issue by rguikers** [jerryjliu/llama_index#803] opened 2023-03-20 14:23 UTC
When saving the index (GPTSimpleVectorIndex save_to_disk) and eventually loading the index 

```
index = GPTSimpleVectorIndex.load_from_disk('index.json')
response = index.query(input_text, response_mode="compact")
```
results in : 
```
INFO:openai:error_code=DeploymentNotFound error_message='The API deployment for this resource does not exist. If you created the deployment within the last 5 minutes, please wait a moment and try again.' error_param=None error_type=None message='OpenAI API error received' stream_error=False
```

Using the index right after creating it works fine.

Are there any necessary settings that I'm missing after loading the index?

**Comment by fms-santos** [comment] 2023-03-20 16:12
I'm also having the same issue when using Azure OpenAI

**Comment by Buckler89** [comment] 2023-03-23 13:41
To solve this you can pass all the parameters also to the load_from_* fucntion. For example:

```
# define LLM
llm = AzureOpenAI(deployment_name="**********", model_name="text-davinci-003", temperature=.0, max_tokens=1000)
llm_predictor = LLMPredictor(llm=llm)
embedding_llm = LangchainEmbedding(OpenAIEmbeddings(model="*********"))
index = GPTSimpleVectorIndex.load_from_disk("index.json", llm_predictor=llm_predictor, embed_model=embedding_llm, prompt_helper=prompt_helper)
```

it is working for me.

**Comment by Disiok** [comment] 2023-03-25 02:10
@Buckler89 Thanks for helping to resolve the question! Yep definitely not the most intuitive, we will improve the docs!
Added to the FAQ for now: https://docs.google.com/document/d/1bLP7301n4w9_GsukIYvEhZXVAvOMWnrxMy089TYisXU/edit#

Duplicate of #819

**Closed by Disiok** 2023-03-25 02:10 UTC
