### ISSUE TITLE
怎么配置代理能连接到openAI api？WARNING:urllib3.connectionpool:Retrying

### ISSUE THREAD

**Issue by lvjianxin** [jerryjliu/llama_index#1098] opened 2023-04-07 13:02 UTC
WARNING:urllib3.connectionpool:Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProxyError('Cannot connect to proxy.', OSError('Tunnel connection failed: 400 Bad Request'))': /v1....

**Comment by dominicqi** [comment] 2023-04-07 15:26
you can set https_proxy env

**Comment by Disiok** [comment] 2023-04-08 19:55
Duplicate of https://github.com/jerryjliu/llama_index/issues/640

**Closed by Disiok** 2023-04-08 19:55 UTC
