### ISSUE TITLE
DiscordReader ERROR:asyncio:Unclosed connector

### ISSUE THREAD

**Issue by ardaerturk** [jerryjliu/llama_index#863] opened 2023-03-24 00:42 UTC
I'm trying to use the DiscordReader to create an index for a Discord channel. I'm getting and error.

```
import nest_asyncio
nest_asyncio.apply()

discord_token = os.getenv("DISCORD_TOKEN")
channel_ids = [1057178784895348746]
documents = DiscordReader(discord_token=discord_token).load_data(channel_ids=channel_ids)
index = GPTListIndex(documents)
index.save_to_disk('./index/discord_index.json')
```

Here's the error I'm getting

```
INFO:discord.client:logging in using static token
logging in using static token
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/discord/http.py", line 801, in static_login
    data = await self.request(Route('GET', '/users/@me'))
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/discord/http.py", line 744, in request
    raise HTTPException(response, data)
discord.errors.HTTPException: 401 Unauthorized (error code: 0): 401: Unauthorized

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/backend/support_functions.py", line 122, in <module>

    documents = DiscordReader(discord_token=discord_token).load_data(channel_ids=channel_ids)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/llama_index/readers/discord_reader.py", line 139, in load_data
    channel_content = self._read_channel(
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/llama_index/readers/discord_reader.py", line 107, in _read_channel
    result = asyncio.get_event_loop().run_until_complete(
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/nest_asyncio.py", line 90, in run_until_complete
    return f.result()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/futures.py", line 201, in result
    raise self._exception.with_traceback(self._exception_tb)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/tasks.py", line 232, in __step
    result = coro.send(None)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/llama_index/readers/discord_reader.py", line 67, in read_channel
    await client.start(discord_token)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/discord/client.py", line 777, in start
    await self.login(token)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/discord/client.py", line 612, in login
    data = await self.http.static_login(token)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/discord/http.py", line 805, in static_login
    raise LoginFailure('Improper token has been passed.') from exc
discord.errors.LoginFailure: Improper token has been passed.
ERROR:asyncio:Unclosed connector
connections: ['[(<aiohttp.client_proto.ResponseHandler object at 0x129dd25c0>, 496228.700723916)]']
connector: <aiohttp.connector.TCPConnector object at 0x12e2b5000>
Unclosed connector
connections: ['[(<aiohttp.client_proto.ResponseHandler object at 0x129dd25c0>, 496228.700723916)]']
connector: <aiohttp.connector.TCPConnector object at 0x12e2b5000
```

My understanding is the discord token is an individual user's token, not a bot token and you don't need to be the owner of the server to read the conversations. Please advise

**Comment by Disiok** [comment] 2023-03-25 01:45
Hey @ardaerturk Were you able to access discord API with the token you supplied?

The error message `discord.errors.LoginFailure: Improper token has been passed` seems to suggest that you passed a bad token. 

Going to close this for now, since the issue is unrelated to LlamaIndex. Please join our discord community (https://discord.com/invite/dGcwcsnxhU) where you'd get much better support!

**Closed by Disiok** 2023-03-25 01:45 UTC
Labels: discord
