### ISSUE TITLE
[Question]: KnowledgeGraphIndex NebulaGraph tutorial error

### ISSUE THREAD

**Issue by salahaz** [jerryjliu/llama_index#6509] opened 2023-06-19 12:28 UTC
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

Hello I'm expirementing with the NebulaGraph example thats been released https://github.com/jerryjliu/llama_index/blob/main/docs/examples/index_structs/knowledge_graph/NebulaGraphKGIndexDemo.ipynb. However, during the instantiation of GPTNebulaGraph KG Indexes the following error occurs. Any idea how to resolve this ?

![error](https://github.com/jerryjliu/llama_index/assets/41476094/8c5b5e6a-b609-4e34-8b9b-ad39c987335f)

**Comment by salahaz** [comment] 2023-06-19 14:32
@wey-gu @jerryjliu

**Comment by wey-gu** [comment] 2023-06-19 14:56
This could be due to the extracted triplets are with invalid lines, could you please check out this pr's change and retry?

https://github.com/jerryjliu/llama_index/pull/6497

**Comment by wey-gu** [comment] 2023-06-20 09:50
update, the PR above is merged, could you try with the master of llama_index? This should be resolved.

**Comment by salahaz** [comment] 2023-06-20 13:45
Hello,  instantiating of GPTNebulaGraph KG works now; However, during querying the engine. I receive the following error message: 
![error2](https://github.com/jerryjliu/llama_index/assets/41476094/f8981129-7805-4b79-81e2-ee5738d07531)

**Comment by wey-gu** [comment] 2023-06-21 02:57
> Hello, instantiating of GPTNebulaGraph KG works now; However, during querying the engine. I receive the following error message: ![error2](https://user-images.githubusercontent.com/41476094/247134242-f8981129-7805-4b79-81e2-ee5738d07531.png)

Dear @salahaz , I'll try reproducing this later and fix if it's impl. issue of NebulaGrpah Store, before that, could you instead try the latest tutorial here? https://gpt-index.readthedocs.io/en/latest/examples/index_structs/knowledge_graph/KnowledgeGraphIndex_vs_VectorStoreIndex_vs_CustomIndex_combined.html 

Also, I answered your questions in discord.

**Comment by c2j** [comment] 2023-07-03 04:21
> > Hello, instantiating of GPTNebulaGraph KG works now; However, during querying the engine. I receive the following error message: ![error2](https://user-images.githubusercontent.com/41476094/247134242-f8981129-7805-4b79-81e2-ee5738d07531.png)
> 
> Dear @salahaz , I'll try reproducing this later and fix if it's impl. issue of NebulaGrpah Store, before that, could you instead try the latest tutorial here? https://gpt-index.readthedocs.io/en/latest/examples/index_structs/knowledge_graph/KnowledgeGraphIndex_vs_VectorStoreIndex_vs_CustomIndex_combined.html
> 
> Also, I answered your questions in discord.

Same error in llama_index 0.6.38.post1, Any progress?

**Comment by wey-gu** [comment] 2023-07-03 10:03
@c2j @BleakStone, would you mind sharing a more detailed procedure for reproducing the issue?

like with the same documents? what query?

I cannot reproduce it today( but with Azure OpenAI, though). I tried queries that were getting empty results from the KG, but no errors were encountered. 

ref: https://github.com/jerryjliu/llama_index/pull/6497#discussion_r1247560083

**Comment by c2j** [comment] 2023-07-03 10:48
> @c2j @BleakStone, would you mind sharing a more detailed procedure for reproducing the issue?
> 
> like with the same documents? what query?
> 
> I cannot reproduce it today( but with Azure OpenAI, though). I tried queries that were getting empty results from the KG, but no errors were encountered.
> 
> ref: [#6497 (comment)](https://github.com/jerryjliu/llama_index/pull/6497#discussion_r1247560083)
> 
> ```
> INFO:llama_index.indices.knowledge_graph.retriever:> Starting query: Tell me about Panda
> > Starting query: Tell me about Panda
> > Starting query: Tell me about Panda
> INFO:llama_index.indices.knowledge_graph.retriever:> Query keywords: ['Animal', 'China', 'Endangered', 'Diet', 'Species', 'Panda', 'Bamboo', 'Conservation', 'Habitat', 'Behavior']
> > Query keywords: ['Animal', 'China', 'Endangered', 'Diet', 'Species', 'Panda', 'Bamboo', 'Conservation', 'Habitat', 'Behavior']
> > Query keywords: ['Animal', 'China', 'Endangered', 'Diet', 'Species', 'Panda', 'Bamboo', 'Conservation', 'Habitat', 'Behavior']
> ERROR:llama_index.indices.knowledge_graph.retriever:Index was not constructed with embeddings, skipping embedding usage...
> Index was not constructed with embeddings, skipping embedding usage...
> Index was not constructed with embeddings, skipping embedding usage...
> INFO:llama_index.indices.knowledge_graph.retriever:> Extracted relationships: The following are knowledge triplets in max depth 2 in the form of `subject [predicate, object, predicate_next_hop, object_next_hop ...]`
> > Extracted relationships: The following are knowledge triplets in max depth 2 in the form of `subject [predicate, object, predicate_next_hop, object_next_hop ...]`
> > Extracted relationships: The following are knowledge triplets in max depth 2 in the form of `subject [predicate, object, predicate_next_hop, object_next_hop ...]`
> INFO:llama_index.token_counter.token_counter:> [get_response] Total LLM token usage: 84 tokens
> > [get_response] Total LLM token usage: 84 tokens
> > [get_response] Total LLM token usage: 84 tokens
> INFO:llama_index.token_counter.token_counter:> [get_response] Total embedding token usage: 0 tokens
> > [get_response] Total embedding token usage: 0 tokens
> > [get_response] Total embedding token usage: 0 tokens
> ```

Reproduce:
Version: llama-index==0.6.38.post1
Step "Query with different retrievers" of Steps: https://gpt-index.readthedocs.io/en/v0.6.38.post1/examples/index_structs/knowledge_graph/KnowledgeGraphIndex_vs_VectorStoreIndex_vs_CustomIndex_combined.html

Try to modify llama_index/graph_stores/nebulagraph.py line 344 and 345 will fix temp:
```
        subjs_ = result.column_values("subj") if result else []
        rels_ = result.column_values("flattened_rels") if result else []
```

**Comment by wey-gu** [comment] 2023-07-03 12:31
Dear @c2j 

Thanks! This made me revisit the execute(),  would you mind helping revert your above change and help change the `execute()` function like this to see if the error persists? If so, to share the fault log?

```python
    def execute(self, query: str, param_map: Optional[Dict[str, Any]] = {}) -> Any:
        """Execute query.

        Args:
            query: Query.
            param_map: Parameter map.

        Returns:
            Query result.
        """
        from nebula3.Exception import IOErrorException
        from nebula3.fbthrift.transport.TTransport import TTransportException

        retry = self._retry
        while retry > 0:
            try:
                result = self._session_pool.execute_parameter(query, param_map)
                if result is None: # this could happend and it'll end up with infinite loop as result.is_succeeded() will go to the final exception caught, where retry was not properly set, this is unexpected but, I would like to know what query triggered so.
                    raise ValueError(
                        f"Query failed. Query: {query}, Param: {param_map}"
                    )
                if not result.is_succeeded():
                    raise ValueError(result.error_msg())
                return result
            except (TTransportException, IOErrorException) as e:
                # connection issue, try to recreate session pool
                if retry > 0:
                    retry -= 2
                    # try to recreate session pool
                    self.init_session_pool()
                else:
                    raise e
            except ValueError as e:
                # query failed on db side
                if retry > 0:
                    retry -= 1
                    continue
                else:
                    raise e
            except Exception as e:
                # other exceptions
                if retry > 0:
                    retry -= 1
                    continue
                raise e
```

Thanks!

**Comment by wey-gu** [comment] 2023-07-04 01:59
Dear @c2j ,

Thanks, sorry my previous one was silly to continue after `retry--`.

It's strange to me on exact exception trigger condition here, could you please help give another try with this?

```python
    def execute(self, query: str, param_map: Optional[Dict[str, Any]] = {}) -> Any:
        """Execute query.

        Args:
            query: Query.
            param_map: Parameter map.

        Returns:
            Query result.
        """
        from nebula3.Exception import IOErrorException
        from nebula3.fbthrift.transport.TTransport import TTransportException

        retry = self._retry
        while retry > 0:
            try:
                result = self._session_pool.execute_parameter(query, param_map)
                if result is None:
                    raise ValueError(
                        f"Query failed. Query: {query}, Param: {param_map}"
                    )
                if not result.is_succeeded():
                    raise ValueError(result.error_msg())
                return result
            except (TTransportException, IOErrorException) as e:
                # connection issue, try to recreate session pool
                retry -= 2
                if retry > 0:
                    # try to recreate session pool
                    self.init_session_pool()
                else:
                    logger.error(f"Query failed. Query: {query}, Param: {param_map}")
                    raise e
            except ValueError as e:
                # query failed on db side
                retry -= 1
                if retry > 0:
                    continue
                else:
                    logger.error(f"Query failed. Query: {query}, Param: {param_map}")
                    raise e
            except Exception as e:
                # other exceptions
                retry -= 1
                if retry > 0:
                    continue
                logger.error(f"Query failed. Query: {query}, Param: {param_map}")
                raise e
```

**Comment by c2j** [comment] 2023-07-04 12:24
> Dear @c2j ,
> 
> Thanks, sorry my previous one was silly to continue after `retry--`.
> 
> It's strange to me on exact exception trigger condition here(which should have been raised instead of continue to return None), could you please help give another try with this?
> 
> ```python
>     def execute(self, query: str, param_map: Optional[Dict[str, Any]] = {}) -> Any:
>         """Execute query.
> 
>         Args:
>             query: Query.
>             param_map: Parameter map.
> 
>         Returns:
>             Query result.
>         """
>         from nebula3.Exception import IOErrorException
>         from nebula3.fbthrift.transport.TTransport import TTransportException
> 
>         retry = self._retry
>         while retry > 0:
>             try:
>                 result = self._session_pool.execute_parameter(query, param_map)
>                 if result is None:
>                     raise ValueError(
>                         f"Query failed. Query: {query}, Param: {param_map}"
>                     )
>                 if not result.is_succeeded():
>                     raise ValueError(result.error_msg())
>                 return result
>             except (TTransportException, IOErrorException) as e:
>                 # connection issue, try to recreate session pool
>                 retry -= 2
>                 if retry > 0:
>                     # try to recreate session pool
>                     self.init_session_pool()
>                 else:
>                     logger.error(f"Query failed. Query: {query}, Param: {param_map}")
>                     raise e
>             except ValueError as e:
>                 # query failed on db side
>                 retry -= 1
>                 if retry > 0:
>                     continue
>                 else:
>                     logger.error(f"Query failed. Query: {query}, Param: {param_map}")
>                     raise e
>             except Exception as e:
>                 # other exceptions
>                 retry -= 1
>                 if retry > 0:
>                     continue
>                 logger.error(f"Query failed. Query: {query}, Param: {param_map}")
>                 raise e
> ```

Another error:
```
INFO:llama_index.indices.knowledge_graph.retriever:> Starting query: Tell me events about NASA
DEBUG:openai:message='Request to OpenAI API' method=post path=https://api.openai.com/v1/completions
DEBUG:openai:api_version=None data='{"prompt": ["A question is provided below. Given the question, extract up to 10 keywords from the text. Focus on extracting the keywords that we can use to best lookup answers to the question. Avoid stopwords.\\n---------------------\\nTell me events about NASA\\n---------------------\\nProvide keywords in the following comma-separated format: \'KEYWORDS: <keywords>\'\\n"], "model": "text-davinci-002", "temperature": 0.0, "max_tokens": 256, "top_p": 1, "frequency_penalty": 0, "presence_penalty": 0, "n": 1, "logit_bias": {}}' message='Post details'
DEBUG:urllib3.connectionpool:[https://api.openai.com:443](https://api.openai.com/) "POST /v1/completions HTTP/1.1" 200 None
DEBUG:openai:message='OpenAI API response' path=https://api.openai.com/v1/completions processing_ms=337 request_id=0c0646eee53ffe441539067862a2f91f response_code=200
DEBUG:llama_index.llm_predictor.base:
KEYWORDS: NASA, events
INFO:llama_index.indices.knowledge_graph.retriever:> Query keywords: ['NASA', 'events']
DEBUG:llama_index.graph_stores.nebulagraph:get_flat_rel_map() subjs_param: ['nasa'], query: MATCH (s)-[e:`rel`*..2]-()   WHERE id(s) IN $subjs WITH id(s) AS subj,[rel IN e |   [rel.`predicate`, dst(rel)] ] AS rels RETURN   subj,  REDUCE(acc = collect(NULL), l in rels | acc + l)    AS flattened_rels
ERROR:llama_index.graph_stores.nebulagraph:Query failed. Query: MATCH (s)-[e:`rel`*..2]-()   WHERE id(s) IN $subjs WITH id(s) AS subj,[rel IN e |   [rel.`predicate`, dst(rel)] ] AS rels RETURN   subj,  REDUCE(acc = collect(NULL), l in rels | acc + l)    AS flattened_rels, Param: {'subjs': Value(
    lVal=NList(
         values=[Value(
             sVal='nasa')]))}
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
Cell In[10], line 1
----> 1 response = kg_keyword_query_engine.query(
      2     "Tell me events about NASA"
      3 )
      4 display(Markdown(f"<b>{response}</b>"))

File ~/Data/ENV/lib/python3.8/site-packages/llama_index/indices/query/base.py:23, in BaseQueryEngine.query(self, str_or_query_bundle)
     21 if isinstance(str_or_query_bundle, str):
     22     str_or_query_bundle = QueryBundle(str_or_query_bundle)
---> 23 response = self._query(str_or_query_bundle)
     24 return response

File ~/Data/ENV/lib/python3.8/site-packages/llama_index/query_engine/retriever_query_engine.py:142, in RetrieverQueryEngine._query(self, query_bundle)
    137 query_id = self.callback_manager.on_event_start(
    138     CBEventType.QUERY, payload={EventPayload.QUERY_STR: query_bundle.query_str}
    139 )
    141 retrieve_id = self.callback_manager.on_event_start(CBEventType.RETRIEVE)
--> 142 nodes = self._retriever.retrieve(query_bundle)
    143 self.callback_manager.on_event_end(
    144     CBEventType.RETRIEVE,
    145     payload={EventPayload.NODES: nodes},
    146     event_id=retrieve_id,
    147 )
    149 response = self._response_synthesizer.synthesize(
    150     query_bundle=query_bundle,
    151     nodes=nodes,
    152 )

File ~/Data/ENV/lib/python3.8/site-packages/llama_index/indices/base_retriever.py:21, in BaseRetriever.retrieve(self, str_or_query_bundle)
     19 if isinstance(str_or_query_bundle, str):
     20     str_or_query_bundle = QueryBundle(str_or_query_bundle)
---> 21 return self._retrieve(str_or_query_bundle)

File ~/Data/ENV/lib/python3.8/site-packages/llama_index/indices/knowledge_graph/retriever.py:161, in KGTableRetriever._retrieve(self, query_bundle)
    154         extended_subjs = self._get_keywords(
    155             self._docstore.get_node(node_id).get_content(
    156                 metadata_mode=MetadataMode.LLM
    157             )
    158         )
    159         subjs.update(extended_subjs)
--> 161 rel_map = self._graph_store.get_rel_map(
    162     list(subjs), self.graph_store_query_depth
    163 )
    164 logger.debug(f"rel_map: {rel_map}")
    166 if not rel_map:

File ~/Data/ENV/lib/python3.8/site-packages/llama_index/graph_stores/nebulagraph.py:380, in NebulaGraphStore.get_rel_map(self, subjs, depth)
    377     if len(subjs) == 0:
    378         return {}
--> 380 return self.get_flat_rel_map(subjs, depth)

File ~/Data/ENV/lib/python3.8/site-packages/llama_index/graph_stores/nebulagraph.py:352, in NebulaGraphStore.get_flat_rel_map(self, subjs, depth)
    350 subjs_param = prepare_subjs_param(subjs)
    351 logger.debug(f"get_flat_rel_map() subjs_param: {subjs}, query: {query}")
--> 352 result = self.execute(query, subjs_param)
    354 # get raw data
    355 subjs_ = result.column_values("subj") or []

File ~/Data/ENV/lib/python3.8/site-packages/llama_index/graph_stores/nebulagraph.py:196, in NebulaGraphStore.execute(self, query, param_map)
    194     else:
    195         logger.error(f"Query failed. Query: {query}, Param: {param_map}")
--> 196         raise e
    197 except Exception as e:
    198     # other exceptions
    199     retry -= 1

File ~/Data/ENV/lib/python3.8/site-packages/llama_index/graph_stores/nebulagraph.py:178, in NebulaGraphStore.execute(self, query, param_map)
    174         raise ValueError(
    175             f"Query failed. Query: {query}, Param: {param_map}"
    176         )
    177     if not result.is_succeeded():
--> 178         raise ValueError(result.error_msg())
    179     return result
    180 except (TTransportException, IOErrorException) as e:
    181     # connection issue, try to recreate session pool

ValueError: Scan vertices or edges need to specify a limit number, or limit number can not push down.
```

**Comment by wey-gu** [comment] 2023-07-04 12:42
Thanks a lot @c2j , this is exactly what's expected now, could I know which version of NebulaGraph are you using, please?

```
ValueError: Scan vertices or edges need to specify a limit number, or limit number can not push down.
```

**Comment by c2j** [comment] 2023-07-04 12:50
> Thanks a lot @c2j , this is exactly what's expected now, could I know which version of NebulaGraph are you using, please?
> 
> ```
> ValueError: Scan vertices or edges need to specify a limit number, or limit number can not push down.
> ```

I start nebula via docker-compose, the image version is `vesoft/nebula-graphd:v3.2.0`

**Comment by wey-gu** [comment] 2023-07-04 12:54
> > Thanks a lot @c2j , this is exactly what's expected now, could I know which version of NebulaGraph are you using, please?
> > ```
> > ValueError: Scan vertices or edges need to specify a limit number, or limit number can not push down.
> > ```
> 
> I start nebula via docker-compose, the image version is `vesoft/nebula-graphd:v3.2.0`

Oh, that's the reason, such queries were not porperly handled in opetimizer thus ending up with the error "cannot push down". Would you mind upgrading the cluster to v3.5.0? Just compose down and update tags, then compose pull and up will do the job, 3.x underlying data are compatible.

Also, I'll update the nebulagraph.py to address the unexpected None, it should raise an exception here with query errors.

**Comment by c2j** [comment] 2023-07-05 04:07
> > > Thanks a lot @c2j , this is exactly what's expected now, could I know which version of NebulaGraph are you using, please?
> > > ```
> > > ValueError: Scan vertices or edges need to specify a limit number, or limit number can not push down.
> > > ```
> > 
> > 
> > I start nebula via docker-compose, the image version is `vesoft/nebula-graphd:v3.2.0`
> 
> Oh, that's the reason, such queries were not porperly handled in opetimizer thus ending up with the error "cannot push down". Would you mind upgrading the cluster to v3.5.0? Just compose down and update tags, then compose pull and up will do the job, 3.x underlying data are compatible.
> 
> Also, I'll update the nebulagraph.py to address the unexpected None, it should raise an exception here with query errors.

After upgrade to v3.5.0, it passed no error.

**Comment by wey-gu** [comment] 2023-07-11 10:39
- [ ] Add NebulaGraph version notice in documentation #6642 
- [ ] optimize NebulaGraph Store implementation #6642

**Closed** 2023-08-24 11:50 UTC
Labels: question
