### ISSUE TITLE
[Question]: KeyError when using VectorStoreIndex.from_documents for text embedding

### ISSUE THREAD

**Issue by Ethan-Gu** [jerryjliu/llama_index#6938] opened 2023-07-17 09:09 UTC
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

Hi all,

I used llama-index(0.7.9) for text embedding. When my document is small, it works fine. When two nodes are got from my documents, there raise a KeyError.

```
documents = SimpleDirectoryReader(input_files=['data/basic_case.json']).load_data()
index = VectorStoreIndex.from_documents(documents, service_context=service_context)
```
Here is the Error:
```
File "/venv/lib/python3.9/site-packages/llama_index/indices/vector_store/base.py", in _get_node_embedding_results
 embedding = id_to_embed_map[node.node_id]
KeyError: '660bc961-55bb-4bd7-8211-880f31423ee5'
```
I print the response from "gpt-3.5-turbo", and it seems to return only one element in the response data. Thus only one node id is added to `id_to_embed_map` when using `zip`. 
```
        # call embedding model to get embeddings
        (
            result_ids,
            result_embeddings,
        ) = self._service_context.embed_model.get_queued_text_embeddings(show_progress)
        for new_id, text_embedding in zip(result_ids, result_embeddings):
            id_to_embed_map[new_id] = text_embedding

        results = []
        for node in nodes:
            embedding = id_to_embed_map[node.node_id]
            result = NodeWithEmbedding(node=node, embedding=embedding)
            results.append(result)
        return results
```
Is it because my document is too long? Could you please tell me how to use it correctly?
Thanks

**Comment by logan-markewich** [comment] 2023-07-19 21:29
I've never seen this issue before 🤔 I don't thiiiink it's related to the length of the data.

Are you able to provide some kind of test case I can use to reproduce the issue on my end?

**Comment by Ethan-Gu** [comment] 2023-07-20 03:10
This will raise the error in my case.
[testcase.txt](https://github.com/jerryjliu/llama_index/files/12101727/testcase.txt)

**Comment by 903496130** [comment] 2023-07-26 07:08
@logan-markewich @Ethan-Gu I got the same problem in my project. It was very easy to make it happen . I just put one txt file which full with chinese words. I try to debug and find out the reason, then i notice that map this place case this error:

File: llama_index/indices/vector_store/base.py,Line 108 ~ 113
<img width="876" alt="image" src="https://github.com/jerryjliu/llama_index/assets/50199902/09728910-5149-45a2-8780-349f396d01fa">

=================

Opps,  I got the reason. You use microsoft auzre api against openai, right?  Auzre api doesn't support input in list form, just string. So when script embedding, input a 3 length list in,but just get a 1 length list out, the error occur.

**Comment by logan-markewich** [comment] 2023-07-26 16:21
@903496130 yea, I've seen the common fix for this is to just set the emebd batch size to 1, then it seems to work

Check out the azure guide here
https://gpt-index.readthedocs.io/en/latest/examples/customization/llms/AzureOpenAI.html

**Closed** 2023-08-17 11:42 UTC
Labels: question
