### ISSUE TITLE
How to fixed "ValueError: A single term is larger than the allowed chunk size."

### ISSUE THREAD

**Issue by yirenkeji555** [jerryjliu/llama_index#453] opened 2023-02-16 02:30 UTC
Error msg: 
ValueError: A single term is larger than the allowed chunk size.
Term size: 510
Chunk size: 379Effective chunk size: 379

<img width="1093" alt="image" src="https://user-images.githubusercontent.com/48214423/219252606-e1d3f6a8-aef0-44a2-99f1-053d184871c4.png">

**Comment by jerryjliu** [comment] 2023-02-16 06:54
@yirenkeji555 what version are you on?

**Comment by jerryjliu** [comment] 2023-02-17 06:09
Got it; would you be able to send me some sample code to reproduce?

**Comment by yirenkeji555** [comment] 2023-02-17 06:15
OK, I just use new content to replace file content in "examples/test_wiki/data/nyc_text.txt".

Attachment is my new content.

[nyc_text.txt](https://github.com/jerryjliu/gpt_index/files/10763736/nyc_text.txt)

**Comment by yirenkeji555** [comment] 2023-02-17 06:24
Comment " request wiki content write to nyc_text.txt" code when you run "examples/test_wiki/TestNYC.ipynb".

**Comment by jerryjliu** [comment] 2023-03-06 22:42
hi @yirenkeji555, apologies for the delay. taking a look now

**Comment by MZhao-ouo** [comment] 2023-03-07 04:43
I have upgraded llama_index to version 0.4.21 and I am still experiencing some issues. Additionally, I was wondering if you could provide me with some guidance on which method would be best suited to load the documents?

**Comment by liyuankui** [comment] 2023-03-07 05:13
same issue met, with SmpleDirectoryReader and GPTTreeIndex.

**Comment by liyuankui** [comment] 2023-03-07 06:12
It might be a Chinese only issue. I replaced all "，" as space, now it works. 
One possible reason is that Chinese is NOT separated by spaces like English or other latin languages.

**Comment by jerryjliu** [comment] 2023-03-07 06:27
This should be fixed with the upcoming release! I took a stab in #628 #629 - we hard force splits if the default separator (space) doesn't work

**Comment by jerryjliu** [comment] 2023-03-07 06:27
though of course if @yirenkeji555 if you have sample data for me to repo, i can verify

**Comment by e0v1a** [comment] 2023-03-07 09:46
Same problem in 0.4.21

**Comment by blackstorm** [comment] 2023-03-10 03:08
@chun1617 The link showing access denied.

**Comment by e0v1a** [comment] 2023-03-10 09:15
> OK, I just use new content to replace file content in "examples/test_wiki/data/nyc_text.txt".
> 
> Attachment is my new content.
> 
> [nyc_text.txt](https://github.com/jerryjliu/gpt_index/files/10763736/nyc_text.txt)

@jerryjliu here is a sample data

**Comment by hackhy** [comment] 2023-03-11 09:27
same issue on 0.4.24. here is the sample data

https://ethbill.s3.ap-southeast-1.amazonaws.com/1.txt
@jerryjliu

**Comment by madawei2699** [comment] 2023-03-12 08:27
same issue on 0.4.26, here is the sample data
[temp.txt](https://github.com/jerryjliu/gpt_index/files/10950312/temp.txt)
@jerryjliu

**Comment by jerryjliu** [comment] 2023-03-12 17:48
Hi @madawei2699, thanks for sharing! Will take a look at a fix verysoon

**Comment by Assazm** [comment] 2023-03-15 06:37
same issue on 0.4.28. here is the sample data
![image](https://user-images.githubusercontent.com/34444627/225226690-7f2ba07f-5559-4ec1-9ed5-894f9e5e0534.png)


https://mp.weixin.qq.com/s/eAP2_TUyoF9uVjUb6cUWYw

**Comment by chrischjh** [comment] 2023-03-19 06:55
same issue 0.4.31

**Comment by jerryjliu** [comment] 2023-03-19 07:06
Hey all,

sorry for the delay on this. Will take a look at sample data that some of you have provided and fix soon. In the meantime you can try manually setting the chunk size through `chunk_size_limit` when building the index

**Comment by suling-fun** [comment] 2023-03-24 16:16
Currently, the encoding method used by `globals_helper.tokenizer` will result in a much higher token count when calculating the number of tokens in Chinese text.
For example:
```
text = '唐高宗仪凤二年春天，六祖大师从广州法性寺来到曹溪南华山宝林寺，\
        韶州刺史韦璩和他的部属入山礼请六祖到城裡的大梵寺讲堂，为大众广开佛法因缘，演说法要。\
        六祖登坛陞座时，闻法的人有韦刺史和他的部属三十多人，以及当时学术界的领袖、学者等三十多人，\
        暨僧、尼、道、俗一千馀人，同时向六祖大师礼座，希望听闻佛法要义。'

encoding = tiktoken.encoding_for_model('gpt-3.5-turbo')
print(len(encoding.encode(text)))
# 218

encoding = tiktoken.get_encoding("gpt2")
print(len(encoding.encode(text)))
# 342
```

**Comment by yaohongfenglove** [comment] 2023-03-25 04:12
### I have the same problem：
```
ValueError: A single term is larger than the allowed chunk size.
Term size: 673
Chunk size: 500Effective chunk size: 500
```

### The source code is as follows, and the data is shown in the attachment

```
# coding=utf8

from llama_index import GPTSimpleVectorIndex, Document
import os


def main():
    os.environ['OPENAI_API_KEY'] = 'sk-XX'
    os.environ['CURL_CA_BUNDLE'] = ''

    # Loading from strings, assuming you saved your data to strings text1, text2, ...
    with open(file="wiki_kuangbiao.txt", mode="r", encoding="utf-8") as f:
        text_wiki_kuangbiao = f.read()

    text_list = [text_wiki_kuangbiao, ]
    documents = [Document(t) for t in text_list]

    # Construct a simple vector index
    index = GPTSimpleVectorIndex(documents, chunk_size_limit=500)

    # Save your index to a index.json file
    index.save_to_disk('index_wiki_kuangbiao.json')

    # Load the index from your saved index.json file
    index = GPTSimpleVectorIndex.load_from_disk('index_wiki_kuangbiao.json')

    # Querying the index
    response = index.query("《狂飙》男一号是？")

    print(response)


if __name__ == '__main__':
    main()
```
[wiki_kuangbiao.txt](https://github.com/jerryjliu/llama_index/files/11067938/wiki_kuangbiao.txt)

**Comment by snipersteve** [comment] 2023-03-26 12:33
i have to set chunk_size_limit to about 2000 to avoid this error, any better solutions?

**Comment by neove** [comment] 2023-03-29 00:25
same problem

**Comment by loi-nguyen-khanh** [comment] 2023-04-05 07:56
I got same issue. And I fixed by this way. It work fine to me.
`
def trim_text(text):
    """
    Trim text
    @param text:
    @return:
    """
    text = text.strip()
    text = re.sub('\s+', ' ', text)
    text = re.sub('\n+', '\n', text)

    return text


def limit_line_length(text):
    """
    Limit line length
    @param text:
    @return:
    """
    lines = []
    for line in text.split('\n'):
        chunks = [line[i:i+MAX_TEXT_INLINE] for i in range(0, len(line), MAX_TEXT_INLINE)]
        lines.extend(chunks)
    return '\n'.join(lines)

########################

documents = SimpleDirectoryReader(folder_path).load_data()
for document in documents:
    document.text = utils_service.limit_line_length(utils_service.trim_text(document.text))

`

**Comment by zijie0** [comment] 2023-04-20 01:52
The problem is that default separator for splitting text in `TokenTextSplitter` is " ". But in languages like Chinese, there might be long text chunks without any whitespaces. So the easiest fix is to increase the `chunk_size_limit`. Or you need to roll out your own text preprocessor.

**Comment by justinzyw** [comment] 2023-05-18 05:42
is there any update on this one please? it is related to pull request #1354 please?

**Comment by yaohongfenglove** [comment] 2023-05-18 05:42
姚宏锋已收到您的来信，谢谢。

**Comment by logan-markewich** [comment] 2023-06-05 15:29
Going to close this issue for now, as this thread has a few good solutions (mainly, setting the separator is probably the ideal solution!)

**Closed by logan-markewich** 2023-06-05 15:29 UTC
Labels: bug, international

**Comment by logan-markewich** [comment] 2023-06-07 01:15
As a summary, there are a few ways to solve this. For example, you can set the seperator like this:

```python
from llama_index.langchain_helpers.text_splitter import TokenTextSplitter
from llama_index.node_parser import SimpleNodeParser
from llama_index import GPTVectorStoreIndex, SimpleDirectoryReader, ServiceContext

splitter = TokenTextSplitter(separator="。")
node_parser = SimpleNodeParser(text_splitter=splitter)
service_context = ServiceContext.from_defaults(node_parser=node_parser)

documents = SimpleDirectoryReader("./data").load_data()

index = GPTVectorStoreIndex.from_documents(documents, service_context=service_context)

response = index.as_query_engine().query("Tell me something about New York")
```


Or as another user suggested, just pre-process the documents instead of customizing the splitter:

```python
for doc in documents:
    # replace all Chinese periods to add whitespaces
    doc.text = doc.text.replace("。", ". ")
```
