### ISSUE TITLE
TestEssay.py AssertionError

### ISSUE THREAD

**Issue by BlackBirds** [jerryjliu/llama_index#680] opened 2023-03-10 02:59 UTC
➜  paul_graham_essay git:(main) ✗ python3 TestEssay.py
Traceback (most recent call last):
  File "/Users/fengwei/temp/gpt_index/examples/paul_graham_essay/TestEssay.py", line 42, in <module>
    index = GPTTreeIndex(documents)
  File "/Users/fengwei/Library/Python/3.9/lib/python/site-packages/llama_index/indices/tree/base.py", line 74, in __init__
    super().__init__(
  File "/Users/fengwei/Library/Python/3.9/lib/python/site-packages/llama_index/indices/base.py", line 83, in __init__
    self._embed_model = embed_model or OpenAIEmbedding()
  File "/Users/fengwei/Library/Python/3.9/lib/python/site-packages/llama_index/embeddings/openai.py", line 208, in __init__
    super().__init__()
  File "/Users/fengwei/Library/Python/3.9/lib/python/site-packages/llama_index/embeddings/base.py", line 55, in __init__
    self._tokenizer: Callable = globals_helper.tokenizer
  File "/Users/fengwei/Library/Python/3.9/lib/python/site-packages/llama_index/utils.py", line 38, in tokenizer
    enc = tiktoken.get_encoding("gpt2")
  File "/Users/fengwei/Library/Python/3.9/lib/python/site-packages/tiktoken/registry.py", line 63, in get_encoding
    enc = Encoding(**constructor())
  File "/Users/fengwei/Library/Python/3.9/lib/python/site-packages/tiktoken_ext/openai_public.py", line 11, in gpt2
    mergeable_ranks = data_gym_to_mergeable_bpe_ranks(
  File "/Users/fengwei/Library/Python/3.9/lib/python/site-packages/tiktoken/load.py", line 90, in data_gym_to_mergeable_bpe_ranks
    assert bpe_ranks == encoder_json_loaded
AssertionError

**Comment by Disiok** [comment] 2023-03-12 04:27
Looks like an issue in the tiktoken installation. Could you check which version is installed in your environment?

**Comment by mobilestack** [comment] 2023-03-14 12:59
> 

I have met almost the same error, and I use tiktoken 0.3.1

**Comment by Disiok** [comment] 2023-03-25 01:27
Duplicate of https://github.com/jerryjliu/llama_index/issues/738

**Closed by Disiok** 2023-03-25 01:27 UTC
