### ISSUE TITLE
on Azure OpenAI, load from json, query index from it, an error occured

### ISSUE THREAD

**Issue by yongxin-ms** [jerryjliu/llama_index#762] opened 2023-03-16 08:37 UTC
I am using these models:
deployment_name = "text-davinci-003"
document_model = "text-embedding-ada-002"
query_model = "text-embedding-ada-002"

it's on Azure OpenAI

When it creates the index and runs, everything is fine, but when saves it to a json file, then loads from it, then query index from it, an error occured like this:

`
InvalidRequestError: Must provide an 'engine' or 'deployment_id' parameter to create a <class 'openai.api_resources.completion.Completion'>
Traceback:
File "C:\Users\yongxin\scoop\apps\python\current\Lib\site-packages\streamlit\runtime\scriptrunner\script_runner.py", line 565, in _run_script
    exec(code, module.__dict__)
File "D:\5_OpenAI\spring-apps-bot\app.py", line 85, in <module>
    response = query_index(index, text)
               ^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Users\yongxin\scoop\apps\python\current\Lib\site-packages\streamlit\runtime\caching\cache_utils.py", line 194, in wrapper
    return cached_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Users\yongxin\scoop\apps\python\current\Lib\site-packages\streamlit\runtime\caching\cache_utils.py", line 223, in __call__
    return self._get_or_create_cached_value(args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Users\yongxin\scoop\apps\python\current\Lib\site-packages\streamlit\runtime\caching\cache_utils.py", line 248, in _get_or_create_cached_value
    return self._handle_cache_miss(cache, value_key, func_args, func_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Users\yongxin\scoop\apps\python\current\Lib\site-packages\streamlit\runtime\caching\cache_utils.py", line 302, in _handle_cache_miss
    computed_value = self._info.func(*func_args, **func_kwargs)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "D:\5_OpenAI\spring-apps-bot\app.py", line 74, in query_index
    response = _index.query(query_text)
               ^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Users\yongxin\scoop\apps\python\current\Lib\site-packages\llama_index\indices\base.py", line 419, in query
    return query_runner.query(query_str, self._index_struct)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Users\yongxin\scoop\apps\python\current\Lib\site-packages\llama_index\indices\query\query_runner.py", line 149, in query
    return query_obj.query(query_bundle)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Users\yongxin\scoop\apps\python\current\Lib\site-packages\llama_index\token_counter\token_counter.py", line 84, in wrapped_llm_predict
    f_return_val = f(_self, *args, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Users\yongxin\scoop\apps\python\current\Lib\site-packages\llama_index\indices\query\base.py", line 383, in query
    response = self._query(query_bundle)
               ^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Users\yongxin\scoop\apps\python\current\Lib\site-packages\llama_index\indices\query\base.py", line 359, in _query
    response_str = self._give_response_for_nodes(query_bundle.query_str)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Users\yongxin\scoop\apps\python\current\Lib\site-packages\llama_index\indices\query\base.py", line 251, in _give_response_for_nodes
    response = self.response_builder.get_response(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Users\yongxin\scoop\apps\python\current\Lib\site-packages\llama_index\indices\response\builder.py", line 318, in get_response
    return self._get_response_default(query_str, prev_response)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Users\yongxin\scoop\apps\python\current\Lib\site-packages\llama_index\indices\response\builder.py", line 201, in _get_response_default
    return self.get_response_over_chunks(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Users\yongxin\scoop\apps\python\current\Lib\site-packages\llama_index\indices\response\builder.py", line 183, in get_response_over_chunks
    response = self.give_response_single(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Users\yongxin\scoop\apps\python\current\Lib\site-packages\llama_index\indices\response\builder.py", line 144, in give_response_single
    response, _ = self.llm_predictor.predict(
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Users\yongxin\scoop\apps\python\current\Lib\site-packages\llama_index\langchain_helpers\chain_wrapper.py", line 133, in predict
    llm_prediction = self._predict(prompt, **prompt_args)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Users\yongxin\scoop\apps\python\current\Lib\site-packages\llama_index\langchain_helpers\chain_wrapper.py", line 107, in _predict
    llm_prediction = retry_on_exceptions_with_backoff(
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Users\yongxin\scoop\apps\python\current\Lib\site-packages\llama_index\utils.py", line 162, in retry_on_exceptions_with_backoff
    return lambda_fn()
           ^^^^^^^^^^^
File "C:\Users\yongxin\scoop\apps\python\current\Lib\site-packages\llama_index\langchain_helpers\chain_wrapper.py", line 108, in <lambda>
    lambda: llm_chain.predict(**full_prompt_args),
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Users\yongxin\scoop\apps\python\current\Lib\site-packages\langchain\chains\llm.py", line 151, in predict
    return self(kwargs)[self.output_key]
           ^^^^^^^^^^^^
File "C:\Users\yongxin\scoop\apps\python\current\Lib\site-packages\langchain\chains\base.py", line 116, in __call__
    raise e
File "C:\Users\yongxin\scoop\apps\python\current\Lib\site-packages\langchain\chains\base.py", line 113, in __call__
    outputs = self._call(inputs)
              ^^^^^^^^^^^^^^^^^^
File "C:\Users\yongxin\scoop\apps\python\current\Lib\site-packages\langchain\chains\llm.py", line 57, in _call
    return self.apply([inputs])[0]
           ^^^^^^^^^^^^^^^^^^^^
File "C:\Users\yongxin\scoop\apps\python\current\Lib\site-packages\langchain\chains\llm.py", line 118, in apply
    response = self.generate(input_list)
               ^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Users\yongxin\scoop\apps\python\current\Lib\site-packages\langchain\chains\llm.py", line 62, in generate
    return self.llm.generate_prompt(prompts, stop)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Users\yongxin\scoop\apps\python\current\Lib\site-packages\langchain\llms\base.py", line 107, in generate_prompt
    return self.generate(prompt_strings, stop=stop)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Users\yongxin\scoop\apps\python\current\Lib\site-packages\langchain\llms\base.py", line 140, in generate
    raise e
File "C:\Users\yongxin\scoop\apps\python\current\Lib\site-packages\langchain\llms\base.py", line 137, in generate
    output = self._generate(prompts, stop=stop)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Users\yongxin\scoop\apps\python\current\Lib\site-packages\langchain\llms\openai.py", line 274, in _generate
    response = completion_with_retry(self, prompt=_prompts, **params)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Users\yongxin\scoop\apps\python\current\Lib\site-packages\langchain\llms\openai.py", line 98, in completion_with_retry
    return _completion_with_retry(**kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Users\yongxin\scoop\apps\python\current\Lib\site-packages\tenacity\__init__.py", line 289, in wrapped_f
    return self(f, *args, **kw)
           ^^^^^^^^^^^^^^^^^^^^
File "C:\Users\yongxin\scoop\apps\python\current\Lib\site-packages\tenacity\__init__.py", line 379, in __call__
    do = self.iter(retry_state=retry_state)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Users\yongxin\scoop\apps\python\current\Lib\site-packages\tenacity\__init__.py", line 314, in iter
    return fut.result()
           ^^^^^^^^^^^^
File "C:\Users\yongxin\scoop\apps\python\current\Lib\concurrent\futures\_base.py", line 449, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
File "C:\Users\yongxin\scoop\apps\python\current\Lib\concurrent\futures\_base.py", line 401, in __get_result
    raise self._exception
File "C:\Users\yongxin\scoop\apps\python\current\Lib\site-packages\tenacity\__init__.py", line 382, in __call__
    result = fn(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^
File "C:\Users\yongxin\scoop\apps\python\current\Lib\site-packages\langchain\llms\openai.py", line 96, in _completion_with_retry
    return llm.client.create(**kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Users\yongxin\scoop\apps\python\current\Lib\site-packages\openai\api_resources\completion.py", line 25, in create
    return super().create(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Users\yongxin\scoop\apps\python\current\Lib\site-packages\openai\api_resources\abstract\engine_api_resource.py", line 149, in create
    ) = cls.__prepare_create_request(
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Users\yongxin\scoop\apps\python\current\Lib\site-packages\openai\api_resources\abstract\engine_api_resource.py", line 83, in __prepare_create_request
    raise error.InvalidRequestError(
`

thanks

**Comment by Disiok** [comment] 2023-03-25 02:20
Duplicate of https://github.com/jerryjliu/llama_index/issues/819

**Closed by Disiok** 2023-03-25 02:20 UTC
